export const LOAD_DEMANDE = "LOAD_DEMANDE"
export const GET_ALL_DEMANDE_SUCCESS = "GET_ALL_DEMANDE_SUCCESS"
export const GET_ALL_DEMANDE_FAIL = "GET_ALL_DEMANDE_FAIL"

export const ADD_DEMANDE_SUCCESS = "ADD_DEMANDE_SUCCESS"
export const ADD_DEMANDE_FAIL = "ADD_DEMANDE_FAIL"

export const DELETE_DEMANDE_SUCCESS = "DELETE_DEMANDE_SUCCESS"
export const DELETE_DEMANDE_FAIL = "DELETE_DEMANDE_FAIL"

export const GET_DEMANDE_SUCCESS = "GET_DEMANDE_SUCCESS"
export const GET_DEMANDE_FAIL = "GET_DEMANDE_FAIL"


export const GET_ALL_DEMANDE_CLIENT_SUCCESS = "GET_ALL_DEMANDE_CLIENT_SUCCESS"
export const GET_ALL_DEMANDE_CLIENT_FAIL = "GET_ALL_DEMANDE_CLIENT_FAIL"